### ISSUE TITLE
Use ndcube >= 2.0

### ISSUE THREAD

**Issue by hayesla** [sunpy/sunkit-dem#12]
We chatted about this on the PyAstro telecon - but did we decide to use NDCube master or 1.3.2?

**Comment by wtbarnes** [comment]
Let's just jump in the end and say master. By the time this actually sees a release, NDCube 2.0 will be out so we can just pin to >2.0 when that happens

**Comment by hayesla** [comment]
sounds like a plan

**Comment by wtbarnes** [comment]
Though we have just "ndcube" in the `setup.cfg` so when you `pip install -e .` you get the latest stable version so there's some dissonance there I guess

**Comment by wtbarnes** [comment]
`ndcube 2.0` is in beta and will be out soon. We should adapt `sunkit-dem` to 2.0 and pin appropriately. It is likely that 2.0 is going to break a lot of things.
