### ISSUE TITLE
Set up Read the Docs documentation

### ISSUE THREAD

**Issue by namurphy** [sunpy/sunkit-dem#8]

**Comment by PaulJWright** [comment]
I will happily contribute a overviews of a few methods and perhaps example plots if that is something we want? 

For example, with `xrt_dem_iterative2.pro` I have some code that visualises the spline knots and the optimisation process; for the basis pursuit code (Cheung et al 2015) I was plotting the underlying Gaussian components of that contribute to the DEM solution.

**Comment by wtbarnes** [comment]
Since we've set up the infrastructure for this, I'm closing this. Obviously, there's still a long way to go in terms of the actual docs.
